// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGnEfXA9szukb3ldzE8-YfHL_-v8y2RY',
    appId: '1:20806194201:web:091af14c722639a66b8688',
    messagingSenderId: '20806194201',
    projectId: 'authmessaging-3564b',
    authDomain: 'authmessaging-3564b.firebaseapp.com',
    storageBucket: 'authmessaging-3564b.appspot.com',
    measurementId: 'G-BXXG12XTMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD52d1NKNH2y8Apuapzv7JGNKb2JVvq8QE',
    appId: '1:20806194201:android:119053f3257d55ef6b8688',
    messagingSenderId: '20806194201',
    projectId: 'authmessaging-3564b',
    storageBucket: 'authmessaging-3564b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowV0Afe1xqrm187jkCC7eH7UL8BbCKG0',
    appId: '1:20806194201:ios:5a7a215ddd1be9c36b8688',
    messagingSenderId: '20806194201',
    projectId: 'authmessaging-3564b',
    storageBucket: 'authmessaging-3564b.appspot.com',
    androidClientId: '20806194201-nsnvs2lq3rm1adqne7nu6jn90ksoag1v.apps.googleusercontent.com',
    iosClientId: '20806194201-d6c8u9gg43vilba3v3b53v9gd8ece0e9.apps.googleusercontent.com',
    iosBundleId: 'io.launchclub.flutterriverpod',
  );
}
